{% set version = "0.10.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-flextable
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/flextable_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/flextable/flextable_{{ version }}.tar.gz
  sha256: 2a8f53bd9408d4585fe7843286cea3e4079ed14cee85556dde3f5e3c9f20efc6

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-data.table >=1.13.0
    - r-gdtools >=0.4.0
    - r-htmltools
    - r-knitr
    - r-officer >=0.6.7
    - r-ragg
    - r-rlang
    - r-rmarkdown >=2.0
    - r-uuid >=0.1_4
    - r-xml2
  run:
    - r-base
    - r-data.table >=1.13.0
    - r-gdtools >=0.4.0
    - r-htmltools
    - r-knitr
    - r-officer >=0.6.7
    - r-ragg
    - r-rlang
    - r-rmarkdown >=2.0
    - r-uuid >=0.1_4
    - r-xml2

test:
  commands:
    - $R -e "library('flextable')"           # [not win]
    - "\"%R%\" -e \"library('flextable')\""  # [win]

about:
  home: https://davidgohel.github.io/flextable
  dev_url: https://github.com/davidgohel/flextable
  doc_url: https://ardata-fr.github.io/flextable-book/
  license: GPL-3.0-only
  summary: "Use a grammar for creating and customizing pretty tables. The following formats are supported: 'HTML', 'PDF', 'RTF', 'Microsoft Word', 'Microsoft PowerPoint' and R 'Grid Graphics'. 'R Markdown', 'Quarto' and the package 'officer' can be used to produce the result files. The syntax is the same for the user regardless
    of the type of output to be produced. A set of functions allows the creation, definition of cell arrangement, addition of headers or footers, formatting and definition of cell content with text and or images. The package also offers a set of high-level functions that allow tabular reporting of statistical models and
    the creation of complex cross tabulations."
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
